from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch

from openprompt_rs.config import load_config
from openprompt_rs.data import build_dataset
from openprompt_rs.engine.evaluator import evaluate_detection_map50, evaluate_model
from openprompt_rs.engine.trainer import build_criterion, build_dataloader
from openprompt_rs.models import PromptBank, build_model
from openprompt_rs.utils.io import seed_everything


REPO_ROOT = Path(__file__).resolve().parents[1]


def resolve_repo_path(raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path
    return REPO_ROOT / path


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate the rebuilt OpenPrompt research scaffold.")
    parser.add_argument("--config", required=True, help="Path to an experiment YAML config.")
    parser.add_argument("--checkpoint", required=True, help="Checkpoint generated by scripts/train.py.")
    parser.add_argument("--split", choices=["train", "val"], default=None, help="Dataset split to evaluate.")
    parser.add_argument(
        "--metric-set",
        choices=["loss", "detection", "both"],
        default="both",
        help="Whether to compute loss-style metrics, detection metrics, or both.",
    )
    parser.add_argument("--score-threshold", type=float, default=0.05, help="Detection score threshold.")
    parser.add_argument("--nms-iou-threshold", type=float, default=0.3, help="Rotated NMS IoU threshold.")
    parser.add_argument("--max-detections", type=int, default=100, help="Maximum detections per image.")
    args = parser.parse_args()

    config = load_config(args.config)
    experiment_cfg = config["experiment"]
    split = args.split or ("val" if "val_dataset" in config else "train")
    dataset_cfg = config["val_dataset"] if split == "val" and "val_dataset" in config else config["dataset"]
    model_cfg = config["model"]
    criterion_cfg = config["criterion"]

    seed_everything(experiment_cfg["seed"])

    if experiment_cfg["device"].startswith("cuda") and not torch.cuda.is_available():
        experiment_cfg["device"] = "cpu"

    prompt_bank = PromptBank.build_from_files(
        taxonomy_path=resolve_repo_path(experiment_cfg["taxonomy_path"]),
        template_path=resolve_repo_path(experiment_cfg["prompt_template_path"]),
        embedding_dim=model_cfg["embedding_dim"],
        class_names=dataset_cfg["class_names"],
        hierarchy_lambda=model_cfg.get("hierarchy_smoothing_lambda", 0.1),
        use_class_offsets=model_cfg.get("use_class_offsets", True),
    )
    model = build_model(model_cfg=model_cfg, prompt_bank=prompt_bank)
    state = torch.load(resolve_repo_path(args.checkpoint), map_location="cpu")
    model.load_state_dict(state["model"])
    model.to(experiment_cfg["device"])

    dataset = build_dataset(dataset_cfg)
    dataloader = build_dataloader(dataset, batch_size=experiment_cfg["batch_size"], shuffle=False)
    criterion = build_criterion(criterion_cfg).to(experiment_cfg["device"])
    results = {"split": split}

    if args.metric_set in {"loss", "both"}:
        results["loss_metrics"] = evaluate_model(
            model=model,
            dataloader=dataloader,
            criterion=criterion,
            relation_matrix=prompt_bank.hierarchy.relation_matrix,
            confusing_matrix=prompt_bank.hierarchy.confusing_matrix,
            device=experiment_cfg["device"],
        )
    if args.metric_set in {"detection", "both"}:
        results["detection_metrics"] = evaluate_detection_map50(
            model=model,
            dataloader=dataloader,
            device=experiment_cfg["device"],
            class_names=dataset_cfg["class_names"],
            score_threshold=args.score_threshold,
            nms_iou_threshold=args.nms_iou_threshold,
            max_detections=args.max_detections,
        )
    print(json.dumps(results, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
