from __future__ import annotations

import argparse
from pathlib import Path

import torch

from openprompt_rs.config import load_config
from openprompt_rs.data import build_dataset
from openprompt_rs.engine.trainer import build_dataloader
from openprompt_rs.models import PromptBank, build_model
from openprompt_rs.models.pseudo_label import HierarchyConsistentPseudoLabeler, PseudoLabelConfig


REPO_ROOT = Path(__file__).resolve().parents[1]


def resolve_repo_path(raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path
    return REPO_ROOT / path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate hierarchy-consistent pseudo labels.")
    parser.add_argument("--config", required=True, help="Path to an experiment YAML config.")
    parser.add_argument("--checkpoint", required=True, help="Checkpoint generated by scripts/train.py.")
    parser.add_argument("--output", required=True, help="Path to save pseudo labels.")
    args = parser.parse_args()

    config = load_config(args.config)
    experiment_cfg = config["experiment"]
    dataset_cfg = config["dataset"]
    model_cfg = config["model"]

    if experiment_cfg["device"].startswith("cuda") and not torch.cuda.is_available():
        experiment_cfg["device"] = "cpu"

    prompt_bank = PromptBank.build_from_files(
        taxonomy_path=resolve_repo_path(experiment_cfg["taxonomy_path"]),
        template_path=resolve_repo_path(experiment_cfg["prompt_template_path"]),
        embedding_dim=model_cfg["embedding_dim"],
        class_names=dataset_cfg["class_names"],
        hierarchy_lambda=model_cfg.get("hierarchy_smoothing_lambda", 0.1),
        use_class_offsets=model_cfg.get("use_class_offsets", True),
    )
    model = build_model(model_cfg=model_cfg, prompt_bank=prompt_bank)
    state = torch.load(resolve_repo_path(args.checkpoint), map_location="cpu")
    model.load_state_dict(state["model"])
    model.to(experiment_cfg["device"])
    model.eval()

    labeler = HierarchyConsistentPseudoLabeler(
        hierarchy=prompt_bank.hierarchy,
        config=PseudoLabelConfig(**config.get("pseudo_label", {})),
    )

    dataset = build_dataset(dataset_cfg)
    dataloader = build_dataloader(dataset, batch_size=experiment_cfg["batch_size"], shuffle=False)

    exported = []
    kept_total = 0
    with torch.no_grad():
        for batch in dataloader:
            images = batch["images"].to(experiment_cfg["device"])
            outputs = model(images)
            pseudo = labeler.filter(
                outputs=outputs,
                prompt_embeddings=outputs["prompt_embeddings"],
                scene_scores=outputs["scene_scores"],
            )
            for sample_meta, sample_pseudo in zip(batch["meta"], pseudo, strict=True):
                kept_total += int(sample_pseudo["labels"].numel())
                exported.append(
                    {
                        "meta": sample_meta,
                        "boxes": sample_pseudo["boxes"].cpu(),
                        "labels": sample_pseudo["labels"].cpu(),
                        "score": sample_pseudo["score"].cpu(),
                    }
                )

    output_path = resolve_repo_path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(exported, output_path)
    print({"samples": len(exported), "kept_total": kept_total, "output": str(output_path)})


if __name__ == "__main__":
    main()

